export const states = [
    {"name": "Alabama", "code": "AL", "id": "01"},
    {"name": "Alaska", "code": "AK", "id": "02"},
    {"name": "Arizona", "code": "AZ", "id": "04"},
    {"name": "Arkansas", "code": "AR", "id": "05"},
    {"name": "California", "code": "CA", "id": "06"},
    {"name": "Colorado", "code": "CO", "id": "08"},
    {"name": "Connecticut", "code": "CT", "id": "09"},
    {"name": "Delaware", "code": "DE", "id": "10"},
    {"name": "Florida", "code": "FL", "id": "12"},
    {"name": "Georgia", "code": "GA", "id": "13"},
    {"name": "Hawaii", "code": "HI", "id": "15"},
    {"name": "Idaho", "code": "ID", "id": "16"},
    {"name": "Illinois", "code": "IL", "id": "17"},
    {"name": "Indiana", "code": "IN", "id": "18"},
    {"name": "Iowa", "code": "IA", "id": "19"},
    {"name": "Kansas", "code": "KS", "id": "20"},
    {"name": "Kentucky", "code": "KY", "id": "21"},
    {"name": "Louisiana", "code": "LA", "id": "22"},
    {"name": "Maine", "code": "ME", "id": "23"},
    {"name": "Maryland", "code": "MD", "id": "24"},
    {"name": "Massachusetts", "code": "MA", "id": "25"},
    {"name": "Michigan", "code": "MI", "id": "26"},
    {"name": "Minnesota", "code": "MN", "id": "27"},
    {"name": "Mississippi", "code": "MS", "id": "28"},
    {"name": "Missouri", "code": "MO", "id": "29"},
    {"name": "Montana", "code": "MT", "id": "30"},
    {"name": "Nebraska", "code": "NE", "id": "31"},
    {"name": "Nevada", "code": "NV", "id": "32"},
    {"name": "New Hampshire", "code": "NH", "id": "33"},
    {"name": "New Jersey", "code": "NJ", "id": "34"},
    {"name": "New Mexico", "code": "NM", "id": "35"},
    {"name": "New York", "code": "NY", "id": "36"},
    {"name": "North Carolina", "code": "NC", "id": "37"},
    {"name": "North Dakota", "code": "ND", "id": "38"},
    {"name": "Ohio", "code": "OH", "id": "39"},
    {"name": "Oklahoma", "code": "OK", "id": "40"},
    {"name": "Oregon", "code": "OR", "id": "41"},
    {"name": "Pennsylvania", "code": "PA", "id": "42"},
    {"name": "Rhode Island", "code": "RI", "id": "44"},
    {"name": "South Carolina", "code": "SC", "id": "45"},
    {"name": "South Dakota", "code": "SD", "id": "46"},
    {"name": "Tennessee", "code": "TN", "id": "47"},
    {"name": "Texas", "code": "TX", "id": "48"},
    {"name": "Utah", "code": "UT", "id": "49"},
    {"name": "Vermont", "code": "VT", "id": "50"},
    {"name": "Virginia", "code": "VA", "id": "51"},
    {"name": "Washington", "code": "WA", "id": "53"},
    {"name": "West Virginia", "code": "WV", "id": "54"},
    {"name": "Wisconsin", "code": "WI", "id": "55"},
    {"name": "Wyoming", "code": "WY", "id": "56"}
];
